version: "3"
services:
    app:
        container_name: master
        build:
            context: .
            dockerfile: ./jenkins/Dockerfile
        ports:
            - 8080:8080
            - 50000:50000
        volumes:
            - master_data:/var/jenkins_home
volumes:
    master_data:
