version: "3"
services:
    jenkins_master:
        container_name: master
        build:
            context: .
            dockerfile: ./jenkins/Dockerfile
        environment:
            JENKINS_OPTS: '--prefix=/jenkins'
        ports:
            - 80:8080
            - 50000:50000
        volumes:
            - jenkins_master_data:/var/jenkins_home
volumes:
    jenkins_master_data:
